### ISSUE TITLE
Auto-detect VS installation location

### ISSUE THREAD

**Issue by aelij** [microsoft/slngen#190] opened 2020-11-29 10:57 UTC
It would be great if the tool could auto-detect the location. I believe most users do not change the default. Or even use `vswhere`, e.g.:

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/10d125c7c448b6adb350bea04667832484b7092e/src/StructuredLogViewer/MSBuildLocator.cs#L46

It's a bit of a nuisance to rely on the VS command prompt.

**Comment by jeffkl** [comment] 2020-11-30 21:47
Older versions of SlnGen supported this but it got to be a bit complicated.  If you have multiple versions of Visual Studio installed, there's no good way to pick the right one without making the user specify it.  So we opted to have you "select" the Visual Studio installation by using its corresponding Developer Command Prompt.  This provides the most reliable experience.

MSBuildLocator can find all of the instances, and SlnGen can use the same logic.  But picking which one to use is more difficult.

**Comment by aelij** [comment] 2020-12-01 09:58
Does it really matter which one to use? Also, why not use `dotnet msbuild`?

**Comment by aelij** [comment] 2020-12-01 10:02
My motivation was to create an alternative to `.sln` files (I used `.slnx`), so they could be double clicked in File Explorer. I created a file association:

```cmd
reg add "HKEY_CURRENT_USER\Software\Classes\.slnx" /ve /d "SlnGen"
reg add "HKEY_CURRENT_USER\Software\Classes\SlnGen\shell\open\command" /ve /d "cmd /c slngen ""%1"" --folders:true --collapsefolders:true --ignoreMainProject"
```

**Comment by jeffkl** [comment] 2020-12-01 16:06
In order for SlnGen to gather the transitive closure of projects, it must use MSBuild to evaluate them and get the ProjectReferences.  For this to be reliable, SlnGen must use a version of MSBuild that is compatible with a particular repo.  For example, MSBuild 16.7 might ship with a new feature that makes it impossible to load the projects with MSBuild 16.4.  

The problem is compounded by `dotnet msbuild` since this is the .NET Core MSBuild and that ships with the .NET Core SDK.  The .NET Core SDK cannot build/load certain project types like `.vcxproj` (C++) since the C++ SDK only ships with Visual Studio.  Other project types that can't be built with .NET Core include `.ccproj` (Azure SDK), `.sfproj` (Service Fabric). 

So unfortunately, it really does matter which version of MSBuild you use to parse projects and generate solution files.  The errors you get if things are wrong can be quite cryptic and non obvious so SlnGen at the moment requires you to run it from a Developer Command Prompt that is compatible with a particular repo.

**Comment by aelij** [comment] 2020-12-02 08:19
Thanks for the detailed explanation :)

How about adding a command line option that enables `dotnet msbuild` instead of the VS msbuild? This would also make SlnGen cross-platform.

**Comment by jeffkl** [comment] 2020-12-07 17:48
At the moment, cross platform support is a lower priority as the vast majority of SlnGen users are on Windows and generates solutions for Visual Studio.  As more people use VS for Mac this will change the need.  Is there a strong use case for SlnGen to be cross platform otherwise?

**Comment by aelij** [comment] 2020-12-08 14:43
Xplat is not a requirement for us. I was citing it as a side benefit for having a command line option to use `dotnet msbuild`, which would allow running the command without the VS env var.

**Comment by jeffkl** [comment] 2020-12-08 20:52
> which would allow running the command without the VS env var.

Actually this is not entirely true. If my repository uses build logic that is only in .NET 5 and you only have .NET SDK 3.1 installed, there's no guarantee that `dotnet build` would be able to load my projects.  Yes `dotnet` is added to the `PATH` environment variable, but you may still need to specify a version in [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) in order to ensure things work.  Then you add on the fact that there are certain project types that .NET SDK can't build (C++, Azure SDK, etc) and it gets complicated.

The Visual Studio Developer Command Prompt simply adds the corresponding MSBuild to the `PATH` so that SlnGen knowns exactly which one to use.  Although it suffers the same problem, if you are in a command prompt that isn't compatible with my repository, there's no guarantee it will work 😞

We'll keep evaluating options as the .NET developer ecosystem evolves, I think at the moment SlnGen's experience at finding MSBuild is adequate.

**Comment by aelij** [comment] 2020-12-12 10:06
> no guarantee that dotnet build would be able to load my projects

True, but then you would not be able to open those projects in VS (without the proper SDK installed), so I'm not sure this case is really interesting from SlnGen's perspective.

**Comment by jeffkl** [comment] 2020-12-14 18:08
If you do have the SDKs installed, they'll load in Visual Studio and SlnGen can use the MSBuild.exe next to it to be able to parse the projects and generate the solution.  But on the same machine the .NET Core MSBuild would not.  At least if it fails to load projects with the VS MSBuild, you can fix the problem by installing the SDKs.  But with .NET Core MSBuild there's absolutely no way to get it to work if you're using these project types that aren't part of .NET Core SDK.

**Comment by aelij** [comment] 2020-12-15 10:00
That's why I offered an opt-in behavior, e.g. `slngen --dotnetmsbuild`. IMO the risk of someone misusing this is minimal, and even if one were to misuse it, it'd be pretty easy to notice that projects are missing.

**Comment by sagmor** [comment] 2020-12-23 17:14
how about use MSBuild locator and:
IF there is only one VS installation, just pick it
IF there are more, stop and make the user pick one

**Comment by dsbenghe** [comment] 2021-02-13 18:00
How about have the msbuild path as an optional parameter? 

Our build script has its own logic/detection of msbuild to enforce a minimal version of msbuild. 

Opening a command prompt is a hassle and also prevents cases when you want to so something similar like described above - single click to generate and open solution.

**Comment by jeffkl** [comment] 2021-02-18 17:29
@dsbenghe adding a parameter to specify the MSBuild path seems fine.  We already allow you to specify the path to Visual Studio so that would be in line with that feature.  Does anyone want to contribute this feature?

**Comment by jeffkl** [comment] 2021-11-18 19:36
Closing this for now since newer versions of SlnGen use the first compatible `MSBuild` on the `PATH` and only the correct .NET SDK based on the current runtime/global.json.  Feel free to reopen if this issue still persists.

**Closed by jeffkl** 2021-11-18 19:36 UTC
Labels: Feature Request
